stages:
  - build

build-job:
  stage: build
  tags:
    - self-hosted   # Match the tag(s) assigned to your runner
  script:
    - echo "Starting build..."
    - mkdir -p build
    - echo "Hello from GitLab CI Build Stage!" > build/output.txt
    - echo "Build completed."
