name: Debug Build

on:
  workflow_dispatch:

jobs:
  debug-job:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v3
      - name: Print environment info
        run: |
          echo "Current directory: $PWD"
          echo "User: $(whoami)"
          echo "Listing repo contents:"
          ls -la
      - name: Test mkdir
        run: mkdir -p $GITHUB_WORKSPACE/build
      - name: Test echo
        run: echo "Test file" > $GITHUB_WORKSPACE/build/test.txt
      - name: Verify build folder
        run: ls -l $GITHUB_WORKSPACE/build
