name: Build Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-job:
    runs-on: [self-hosted, Linux, X64]
    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Ensure build directory exists
      - name: Create build folder safely
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          echo "Build folder ready"

      # 3. Write output to a file
      - name: Write output file
        run: |
          echo "Hello from GitHub Actions Build Stage!" > $GITHUB_WORKSPACE/build/output.txt
          echo "Output file created at $GITHUB_WORKSPACE/build/output.txt"

      # 4. List contents of the build folder
      - name: Verify build folder contents
        run: |
          echo "Listing build folder contents:"
          ls -l $GITHUB_WORKSPACE/build

      # 5. Confirm completion
      - name: Build completed
        run: echo "Build job completed successfully."
